// Created by iWeb 3.0.4 local-build-20131107

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,258),url:'Artists_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Artists_files/stroke_9.png'},{rect:new IWRect(2,-2,177,4),url:'Artists_files/stroke_10.png'},{rect:new IWRect(179,-2,5,4),url:'Artists_files/stroke_11.png'},{rect:new IWRect(179,2,5,258),url:'Artists_files/stroke_12.png'},{rect:new IWRect(179,260,5,4),url:'Artists_files/stroke_13.png'},{rect:new IWRect(2,260,177,4),url:'Artists_files/stroke_14.png'},{rect:new IWRect(-2,260,4,4),url:'Artists_files/stroke_15.png'}],new IWSize(181,262)),shadow_0:new IWShadow({blurRadius:6,offset:new IWPoint(1.4142,1.4142),color:'#000000',opacity:0.750000}),stroke_1:new IWEmptyStroke(),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,174),url:'Artists_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Artists_files/stroke_1.png'},{rect:new IWRect(1,-1,307,2),url:'Artists_files/stroke_2.png'},{rect:new IWRect(308,-1,2,2),url:'Artists_files/stroke_3.png'},{rect:new IWRect(308,1,2,174),url:'Artists_files/stroke_4.png'},{rect:new IWRect(308,175,2,2),url:'Artists_files/stroke_5.png'},{rect:new IWRect(1,175,307,2),url:'Artists_files/stroke_6.png'},{rect:new IWRect(-1,175,2,2),url:'Artists_files/stroke_7.png'}],new IWSize(309,176))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Artists_files/ArtistsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');fixAllIEPNGs('Media/transparent.gif');Widget.onload();IMpreload('Artists_files','shapeimage_5','0');IMpreload('Artists_files','shapeimage_5','1');fixupIECSS3Opacity('id11');applyEffects()}
function onPageUnload()
{Widget.onunload();}
